# Task : 1 Notebook Structure & Data Loading

## E - commerce Logistics

#### Description : 
##### This porject represents e-commerce logistics and last-mile deiivery operations across Indian regions, suitable for supply chain, delivery performance and customer experience analytics.

### Import requrired Libraries :

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

### Load dataset

In [2]:
df = pd.read_csv('Ecommerce_Logistics_and_Delivery_Gigantic.csv')

#### Dataset Shape :

In [3]:
df.shape

(73500, 10)

#### First & last 5 row

In [4]:
df.head()

,Shipment_ID,Order_Date,Region,City,Delivery_Partner,Shipping_Mode,Delivery_Time_Days,Order_Value,Delivery_Status,Customer_Rating
0,900000,05-09-2022,North,Ahmedabad,Ecom Express,Standard,8.0,171575.41,Delivered,4.0
1,900001,29-03-2023,West,Ahmedabad,BlueDart,Standard,10.0,8628.10,Delayed,3.0
2,900002,23-03-2022,South,Hyderabad,BlueDart,Standard,12.0,161353.25,Cancelled,3.0
3,900003,25-01-2024,West,Hyderabad,Ecom Express,Standard,14.0,57509.48,Delayed,2.0
4,900004,11-11-2023,South,Mumbai,Ecom Express,Standard,14.0,154628.04,Delivered,1.0

In [5]:
df.tail()

,Shipment_ID,Order_Date,Region,City,Delivery_Partner,Shipping_Mode,Delivery_Time_Days,Order_Value,Delivery_Status,Customer_Rating
73495,901870,09-08-2022,East,Kolkata,Ecom Express,Express,7.0,7879.04,Delivered,4.0
73496,915961,20-07-2023,West,Pune,Delhivery,Express,6.0,145610.57,Delivered,3.0
73497,909351,17-09-2023,South,Mumbai,Ecom Express,Express,14.0,140215.59,Delivered,3.0
73498,966364,20-10-2021,Central,Pune,BlueDart,Same-Day,8.0,132471.00,Delayed,5.0
73499,909712,27-03-2022,NaN,NaN,NaN,Standard,13.0,37043.44,Delivered,4.0

#### Information of dataset :

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73500 entries, 0 to 73499
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shipment_ID         73500 non-null  int64
 1   Order_Date          73500 non-null  object
 2   Region              58743 non-null  object
 3   City                65245 non-null  object
 4   Delivery_Partner    65962 non-null  object
 5   Shipping_Mode       73500 non-null  object
 6   Delivery_Time_Days  68652 non-null  float64
 7   Order_Value         73500 non-null  float64
 8   Delivery_Status     69884 non-null  object
 9   Customer_Rating     66117 non-null  float64
dtypes: float64(3), int64(1), object(6)
memory usage: 5.6+ MB

#### Describe of data :

In [7]:
df.describe()

         Shipment_ID  Delivery_Time_Days    Order_Value  Customer_Rating
count   73500.000000        68652.000000   73500.000000     66117.000000
mean   935016.716612            7.541761   99924.325369         3.349577
std     20199.507118            4.041246   57650.901131         1.165733
min    900000.000000            1.000000     302.070000         1.000000
25%    917524.750000            4.000000   49895.900000         3.000000
50%    935034.500000            8.000000   99908.880000         3.000000
75%    952495.250000           11.000000  149806.210000         4.000000
max    969999.000000           14.000000  199999.600000         5.000000

# Task : 2 Data Cleaning & EDA

### Identify and Handling missing Value

###  Data Cleaning

In [8]:
# numerical columns 
num_cols = ['Delivery_Time_Days','Customer_Rating']
for col in num_cols : 
    df[col] = df[col].fillna(df[col].mean()) 

# categorical columns 
cat_cols = ['Region','City','Delivery_Partner','Delivery_Status']
for col in cat_cols : 
    df[col] = df[col].fillna(df[col].mode()[0])

how to handling missing value in data column using pandas?
df['Order_Date'].fillna(method='ffill')

Object `pandas` not found.

C:\Users\aisam\AppData\Local\Temp\ipykernel_13940\200764979.py:12: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Order_Date'].fillna(method='ffill')

0        05-09-2022
1        29-03-2023
2        23-03-2022
3        25-01-2024
4        11-11-2023
            ...
73495    09-08-2022
73496    20-07-2023
73497    17-09-2023
73498    20-10-2021
73499    27-03-2022
Name: Order_Date, Length: 73500, dtype: object

In [9]:
df.isnull().sum()

Shipment_ID           0
Order_Date            0
Region                0
City                  0
Delivery_Partner      0
Shipping_Mode         0
Delivery_Time_Days    0
Order_Value           0
Delivery_Status       0
Customer_Rating       0
dtype: int64

### Change the Order_Date Column DataType

In [10]:
df['Order_Date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 73500 entries, 0 to 73499
Series name: Order_Date
Non-Null Count  Dtype
--------------  -----
73500 non-null  object
dtypes: object(1)
memory usage: 574.3+ KB

In [11]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [12]:
df['Order_Date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 73500 entries, 0 to 73499
Series name: Order_Date
Non-Null Count  Dtype
--------------  -----
29025 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 574.3 KB

### Detect and Handling Duplicate Records

In [15]:
df.duplicated().sum()

np.int64(3500)

In [16]:
df.drop_duplicates()

,Shipment_ID,Order_Date,Region,City,Delivery_Partner,Shipping_Mode,Delivery_Time_Days,Order_Value,Delivery_Status,Customer_Rating
0,900000,2022-05-09,North,Ahmedabad,Ecom Express,Standard,8.0,171575.41,Delivered,4.0
1,900001,NaT,West,Ahmedabad,BlueDart,Standard,10.0,8628.10,Delayed,3.0
2,900002,NaT,South,Hyderabad,BlueDart,Standard,12.0,161353.25,Cancelled,3.0
3,900003,NaT,West,Hyderabad,Ecom Express,Standard,14.0,57509.48,Delayed,2.0
4,900004,2023-11-11,South,Mumbai,Ecom Express,Standard,14.0,154628.04,Delivered,1.0
...,...,...,...,...,...,...,...,...,...,...
69995,969995,NaT,South,Chennai,Ecom Express,Same-Day,6.0,163990.54,Cancelled,1.0
69996,969996,NaT,West,Delhi,Amazon Logistics,Standard,9.0,147283.04,Delivered,4.0
69997,969997,2021-02-11,North,Kolkata,XpressBees,Express,5.0,15280.23,Delivered,5.0
69998,969998,NaT,East,Delhi,Amazon Logistics,Standard,14.0,63749.30,Delivered,4.0
69999,969999,2022-11-05,South,Ahmedabad,Ecom Express,Standard,11.0,18669.67,Delivered,4.0

### Summary Statistics

In [18]:
df.describe()

,Shipment_ID,Order_Date,Delivery_Time_Days,Order_Value,Customer_Rating
count,73500.000000,29025,73500.000000,73500.000000,73500.000000
mean,935016.716612,2022-09-26 13:41:52.744186368,7.541761,99924.325369,3.349577
min,900000.000000,2021-01-06 00:00:00,1.000000,302.070000,1.000000
25%,917524.750000,2022-02-03 00:00:00,4.000000,49895.900000,3.000000
50%,935034.500000,2022-10-05 00:00:00,7.541761,99908.880000,3.349577
75%,952495.250000,2023-06-08 00:00:00,11.000000,149806.210000,4.000000
max,969999.000000,2024-12-02 00:00:00,14.000000,199999.600000,5.000000
std,20199.507118,NaN,3.905692,57650.901131,1.105635

### region-wise distribution

In [21]:
df['Region'].value_counts()

Region
North      26582
South      11800
West       11771
Central    11676
East       11671
Name: count, dtype: int64

# Task : 3 Business / Logistics Data Analysis

### Region - wise delivery Performance

In [24]:
df.groupby('Region')['Delivery_Time_Days'].mean().sort_values()

Region
West       7.514958
East       7.536678
Central    7.541844
North      7.544748
South      7.566715
Name: Delivery_Time_Days, dtype: float64

### Delivery partner vs average delivery time

In [28]:
df.groupby('Delivery_Partner')['Delivery_Time_Days'].mean().sort_values()

Delivery_Partner
XpressBees          7.479444
Ecom Express        7.500829
Amazon Logistics    7.560985
Delhivery           7.574098
BlueDart            7.617261
Name: Delivery_Time_Days, dtype: float64

### Shipping mode impact on delays

In [30]:
df.groupby('Shipping_Mode')['Delivery_Time_Days'].mean()

Shipping_Mode
Express     7.529977
Same-Day    7.546529
Standard    7.548445
Name: Delivery_Time_Days, dtype: float64

### Order value vs Delivery status analysis

In [31]:
df.groupby('Delivery_Status')['Order_Value'].mean()

Delivery_Status
Cancelled    100044.048606
Delayed       99631.325751
Delivered    100019.307970
Name: Order_Value, dtype: float64